// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		ping: {
			/**
			 * Bot responds with pong!
			 */
			description: string
		}
		help: {
			/**
			 * Displays help on bot commands.
			 */
			description: string
		}
		addactivity: {
			/**
			 * Add new activity to the database.
			 */
			description: string
		}
	}
	/**
	 * There was an error while executing this command!
	 */
	errorOnCommand: string
}

export type TranslationFunctions = {
	commands: {
		ping: {
			/**
			 * Bot responds with pong!
			 */
			description: () => LocalizedString
		}
		help: {
			/**
			 * Displays help on bot commands.
			 */
			description: () => LocalizedString
		}
		addactivity: {
			/**
			 * Add new activity to the database.
			 */
			description: () => LocalizedString
		}
	}
	/**
	 * There was an error while executing this command!
	 */
	errorOnCommand: () => LocalizedString
}

export type Formatters = {}
