// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		ping: {
			/**
			 * Bot responds with pong!
			 */
			description: string
		}
		help: {
			/**
			 * Displays help on bot commands.
			 */
			description: string
		}
		addactivity: {
			/**
			 * Add new activity to the database.
			 */
			description: string
			/**
			 * Role for those who enjoy {roleName}. Created by EzBot.
			 * @param {string} roleName
			 */
			roleReason: RequiredParams<'roleName'>
			/**
			 * New activity with name `{activityName}` created.
		A role with the same name has also been created.
		Now you can use dashboard and channel binding for this activity.
			 * @param {string} activityName
			 */
			activityCreated: RequiredParams<'activityName'>
			errors: {
				/**
				 * Activity name is required.
				 */
				propActivityNameIsRequired: string
				/**
				 * Emoji is required and should be valid emoji. For example `:SC2:`.
				 */
				propEmojiShouldBeValidEmoji: string
			}
		}
	}
	/**
	 * There was an error while executing this command!
	 */
	errorOnCommand: string
	/**
	 * yes,yeah,transfer,please,yep,let's go
	 */
	yesPhrases: string
	/**
	 * no,nope,don't,nah,get out
	 */
	noPhrases: string
}

export type TranslationFunctions = {
	commands: {
		ping: {
			/**
			 * Bot responds with pong!
			 */
			description: () => LocalizedString
		}
		help: {
			/**
			 * Displays help on bot commands.
			 */
			description: () => LocalizedString
		}
		addactivity: {
			/**
			 * Add new activity to the database.
			 */
			description: () => LocalizedString
			/**
			 * Role for those who enjoy {roleName}. Created by EzBot.
			 */
			roleReason: (arg: { roleName: string }) => LocalizedString
			/**
			 * New activity with name `{activityName}` created.
		A role with the same name has also been created.
		Now you can use dashboard and channel binding for this activity.
			 */
			activityCreated: (arg: { activityName: string }) => LocalizedString
			errors: {
				/**
				 * Activity name is required.
				 */
				propActivityNameIsRequired: () => LocalizedString
				/**
				 * Emoji is required and should be valid emoji. For example `:SC2:`.
				 */
				propEmojiShouldBeValidEmoji: () => LocalizedString
			}
		}
	}
	/**
	 * There was an error while executing this command!
	 */
	errorOnCommand: () => LocalizedString
	/**
	 * yes,yeah,transfer,please,yep,let's go
	 */
	yesPhrases: () => LocalizedString
	/**
	 * no,nope,don't,nah,get out
	 */
	noPhrases: () => LocalizedString
}

export type Formatters = {}
